version: "3"

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MYSQL_PASSWORD=***
      - MYSQL_DATABASE=***
      - MYSQL_USER=***

  redis:
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud_frontend
    image: hetorusnl/nextcloud-ffmpeg
    ports:
      - 8080:80
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=***
      - MYSQL_DATABASE=***
      - MYSQL_USER=***
      - PHP_UPLOAD_LIMIT=16G
      - PHP_MEMORY_LIMIT=4G
    depends_on:
      - db
      - redis

  cron:
    image: hetorusnl/nextcloud-ffmpeg
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/nextcloud/db
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/nextcloud/nextcloud
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/nextcloud/data
